### ISSUE TITLE
Make the plugin public for other people

### ISSUE THREAD

**Issue by pmochine** [daaru00/gridsome-plugin-i18n#20]
It's a wonderful plugin but it's not public on https://gridsome.org/plugins/.

> Any plugins on NPM can be added to plugin library. Add a **_gridsome-plugin_** keyword in package.json to make it available in the plugin library.

**Comment by daaru00** [comment]
Hi @pmochine,

yep sure! Just waited a while to see if it was stable enough. I'm going to add the keyword and publish on NPM :+1:

**Comment by daaru00** [comment]
now it should be visible in the list :+1: 

![gridsome plugin list](https://user-images.githubusercontent.com/8782994/86507898-deb34700-bddb-11ea-9cfd-d3548578903a.png)
https://gridsome.org/plugins/gridsome-plugin-i18n
