### ISSUE TITLE
Warning from vue-router: Duplicate named routes definition for 404 route

### ISSUE THREAD

**Issue by cfecherolle** [daaru00/gridsome-plugin-i18n#3]
Hello!

As I'm now using your plugin in my personal project, I have a question regarding a router-related  warning showing up in the console when I'm working with `gridsome develop` :

![image](https://user-images.githubusercontent.com/3169480/78453437-04706900-7692-11ea-8e30-07eaa844571f.png)

I think this message is due to the internal workflow of the plugin (creating 2 different 404 routes, one for each of the two languages I have set), have you ever encountered this message? If so, how could we fix the routing and/or the warning about the 404 route?

Thanks in advance! :smile: 

Cécile

**Comment by daaru00** [comment]
Hi @cfecherolle 

yep, it seems there are a strange behaviour coming from [Gridsome core plugin](https://github.com/gridsome/gridsome/blob/bee711c99e52a20fb5213ffa2fb20ed0a46350fd/gridsome/lib/plugins/core/index.js#L38)
```js
if (/\/404\/?/.test(options.path)) {
  options.name = NOT_FOUND_NAME
}
```
it set a fixed name ['404'](https://github.com/gridsome/gridsome/blob/bee711c99e52a20fb5213ffa2fb20ed0a46350fd/gridsome/lib/utils/constants.js#L6) to **all routes that contain** string `/404/`, here the [regex test](https://regex101.com/r/ITWMso/1). Don't know if it should be reported also Gridsome core repo, maybe some `/path/with/404/innocently/inside/` can trigger the same warning.

However, I create a similar plugin's hook and rewrite 404 routes name including locale code into name ([commit](https://github.com/daaru00/gridsome-plugin-i18n/commit/cb2a6691602870b4766a56d0e57d0a6b36957c67#diff-9fd137e3cea1d73377052301c6fea3bfR82-R88)) and deployed a new version [v1.1.1](https://www.npmjs.com/package/gridsome-plugin-i18n/v/1.1.1).

Try to update this module to latest version to check if warning disappear:
```bash
$ npm update gridsome-plugin-i18n
```

Thank you so much for reporting it! I foolishly left the console warnings off and I didn't notice it :sweat_smile: 

Fabio

**Comment by cfecherolle** [comment]
Perfect! I upgraded and the warnings disappeared :smile: :tada: 
That's some weird behaviour for Gridsome core plugin, indeed.

I'll keep reporting stuff I find for the i18n plugin, but I would also like to help (if you need any) and not just "report and wait for things to magically happen" :laughing: 

Anyway, thanks!

**Comment by daaru00** [comment]
> I'll keep reporting stuff I find for the i18n plugin, but I would also like to help (if you need any) and not just "report and wait for things to magically happen"

Really happy to hear this! I've just added a [contributing guide](https://github.com/daaru00/gridsome-plugin-i18n/blob/master/CONTRIBUTING.md) to help to setup a development environment to be able to see and touch the code easily.

Any help is always really appreciated, thank you!
