### ISSUE TITLE
How sort languages?

### ISSUE THREAD

**Issue by antiden** [daaru00/gridsome-plugin-i18n#34]
Hi,

In my case, I have this languages locales: ['en', 'es', 'ch', 'gr'], but in LanguageSwitcher languages ​​are sorted alphabetically. Is it possible to make the languages ​​appear in the order that was specified in the config?

With regards.

**Comment by andre-m5v** [comment]
`$i18n.availableLocales` is a part of the https://github.com/kazupon/vue-i18n api, and the list is being sorted by `vue-i18n`, not this plugin.

To solve your problem you need to get the list of locales into your component in some other way. It depends on where it's coming from initially (api call, local yaml file, hardcoded into config). You could add your list as a collection into Data Store API (https://gridsome.org/docs/data-store-api/) and then request it in `static-query` in your `LanguageSwitcher` component.
