### ISSUE TITLE
Add a feature to $tp, so default language is not prefixed

### ISSUE THREAD

**Issue by pmochine** [daaru00/gridsome-plugin-i18n#6]
Thank you for your working. This package helps a lot! I would love to add one feature to `$tp`. 

With my current settings I generate the links like this:

```
/                    -> component home
/it-it/              -> component home
/en-gb/              -> component home
/en-gb/about         -> component about
/it-it/about         -> component about
/about               -> component about
/it-it/about         -> component about
```

For each link without prefix, the default language is being used. So now using $tp it forces me to `en-gb`. And I don't want to add a prefix only if it's a foreign language (looked at the domain ending).

For more e.g. https://github.com/daaru00/gridsome-plugin-i18n/pull/2#issuecomment-612656753

I hope it's understandable

**Comment by daaru00** [comment]
Yeah, understand what you mean. 

In your opinion, could an option to disable path rewrite for default locale solve this problem? 
Just a `rewriteDefaultLanguage: false` that force to skip the page generation and route rewriting for locale set in `defaultLocale` option

**Comment by pmochine** [comment]
Hey @daaru00  sorry for the late reply. Yes that would be awesome.

Another example: 
When `defaultLocale` is set to `en-gb` and `pathAliases` to `'en-gb': 'en'` 
I still want to see with `$tp('/')` -> `https://mydomain.com` and not `https://mydomain.com/en`

Would it be possible?

**Comment by daaru00** [comment]
yep, I don't see any problems :+1:

**Comment by daaru00** [comment]
Hi @pmochine,

just published some changes into branch feature/no-rewrite-default-locale. Added an option [rewriteDefaultLanguage](https://github.com/daaru00/gridsome-plugin-i18n/tree/feature/no-rewrite-default-locale#rewritedefaultlanguage) that can be set to `false` to have the behaviour you described.

Are you able to do a check if it works as you expect?

**Comment by pmochine** [comment]
@daaru00 Yes it works perfectly 🎉 That's how I expected the behaviour!

**Comment by daaru00** [comment]
Great! I notify you as soon as we release the new version :+1:

**Comment by pmochine** [comment]
@daaru00 Thanks for the pull! It works perfectly. At first, I had a bug, but removing the node_modules folder fixed it. 

Thanks for this amazing plugin :)
