### ISSUE TITLE
child "path" fails because ["path" with value "\de-de\404\" fails to match the leading slash pattern

### ISSUE THREAD

**Issue by mklueh** [daaru00/gridsome-plugin-i18n#8]
Hi @daaru00,

I´ve already mentioned it in https://github.com/daaru00/gridsome-plugin-i18n/issues/1 but I thought I´d create a separate issue to make it easier to find for others.

I´m running into the following issue:

```
Create GraphQL schema - 0.1s
Error: child "path" fails because ["path" with value "\de-de\404\" fails to match the leading slash pattern]
    at validate (C:\Users\MyPC\IdeaProjects\gridsome-i18n\node_modules\gridsome\lib\pages\schemas.js:54:11)
    at Pages.createPage (C:\Users\MyPC\IdeaProjects\gridsome-i18n\node_modules\gridsome\lib\pages\pages.js:165:21)
    at createPage (C:\Users\MyPC\IdeaProjects\gridsome-i18n\node_modules\gridsome\lib\app\actions.js:260:24)
    at VueI18n.createManagedPages (C:\Users\MyPC\IdeaProjects\gridsome-i18n\node_modules\gridsome-plugin-i18n\gridsome.server.js:47:9)
    at Plugins.run (C:\Users\MyPC\IdeaProjects\gridsome-i18n\node_modules\gridsome\lib\app\Plugins.js:141:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Plugins.createPages (C:\Users\MyPC\IdeaProjects\gridsome-i18n\node_modules\gridsome\lib\app\Plugins.js:116:5)
with this configuration
```

```
{
           use: "gridsome-plugin-i18n",
           options: {
               locales: [ 
                   'de-de',
                   'en-us'
               ],
               pathAliases: {
                   'de': 'de',
                   'en': 'en'
               },
               fallbackLocale: 'en-us',
               defaultLocale: 'en-us', 
               messages: {
                   'de-de': require('./src/locales/de-de.json'),
                   'en-gb': require('./src/locales/en-us.json'),
               }
           }
       },
```
Can you reproduce that on your side?

**Comment by daaru00** [comment]
Hi @mklueh,

...your slash are reverse, a correct path should be `/de-de/404/`, maybe I know what's the problem, are you a Windows user right? (just noticed the `C:\`)

I think I wrongly used `path` package to manage the URL path interpolation ([here](https://github.com/daaru00/gridsome-plugin-i18n/blob/1.2.1/gridsome.server.js#L48)), which it operate different in Linux/Unix and Windows OS. I can't reproduce because I'm a Linux user but I'm pretty sure that this is the problem.

**Comment by mklueh** [comment]
Hi @daaru00 ,

thanks for quick answer. Yes indeed I´m on Windows and it would make sense.

What is your setup to test this plugin during development? Do you just copy the source into the node_modules directory of a demo project?

**Comment by daaru00** [comment]
> What is your setup to test this plugin during development? Do you just copy the source into the node_modules directory of a demo project?

Personally I using the "npm link" approach, I added some info about it into [CONTRIBUTING.md](https://github.com/daaru00/gridsome-plugin-i18n/blob/master/CONTRIBUTING.md#getting-started).

Just added some changes to `fix/windows-slash-issue` branch, are you able to perform a test in order to check if now works as expected?

**Comment by daaru00** [comment]
Hi @mklueh,

can I ask you if you managed to test the fix? so I'll close the PR (if it works for you too) and create a new release.

**Comment by mklueh** [comment]
Hi @daaru00 , sorry I have still not managed to try it out :/

**Comment by mklueh** [comment]
Hello @daaru00 , I finally managed to test it and it works perfectly, great work :)


Edit: I´m getting 404 page not found on all routes that are using templates to render like /blog

**Comment by daaru00** [comment]
> Hello @daaru00 , I finally managed to test it and it works perfectly, great work :)

happy to know that it solved your problem! then I'll close the PR and release a new version :+1: 

> Edit: I´m getting 404 page not found on all routes that are using templates to render like /blog

yeah, there are a couple of things that I try to solve related to templates (https://github.com/daaru00/gridsome-plugin-i18n/issues/11). I'm waiting for feedback from the Gridsome core for some changes.
